aa: null  # 自动增强的配置
amp: true  # 是否使用自动混合精度训练
amp_dtype: float16  # 自动混合精度训练的数据类型
amp_impl: native  # 自动混合精度训练的实现方式
aug_repeats: 0  # 数据增强的重复次数
aug_splits: 0  # 数据增强的分割数
batch_size: 8  # 批量大小
bce_loss: false  # 是否使用二元交叉熵损失
bce_pos_weight: null  # 二元交叉熵正类权重
bce_sum: false  # 二元交叉熵损失求和
bce_target_thresh: null  # 二元交叉熵目标阈值
bn_eps: null  # 批归一化的epsilon值
bn_momentum: null  # 批归一化的动量值
channels_last: false  # 是否使用通道后置的数据格式
checkpoint_hist: 10  # 保留的历史检查点数量
class_map: ''  # 类别映射
clip_grad: null  # 梯度裁剪的值
clip_mode: norm  # 梯度裁剪的模式
color_jitter: 0  # 颜色抖动的强度
color_jitter_prob: 0  # 颜色抖动的概率
cooldown_epochs: 0  # 学习率退火后的冷却周期
crop_pct: null  # 裁剪百分比
cutmix: 0.0  # CutMix数据增强的强度
cutmix_minmax: null  # CutMix的最小/最大比率
data: null  # 自定义数据配置
data_dir: E:\clfData  # 数据目录
dataset: ''  # 数据集名称
dataset_download: false  # 是否下载数据集
decay_epochs: 90  # 学习率衰减周期
decay_milestones:  # 学习率衰减里程碑
- 90
- 180
- 270
decay_rate: 0.1  # 学习率衰减率
dist_bn: reduce  # 分布式批归一化的策略
drop: 0.0  # Dropout概率
drop_block: null  # DropBlock配置
drop_connect: null  # DropConnect配置
drop_path: null  # DropPath配置
epoch_repeats: 0.0  # 每个周期的重复次数
epochs: 300  # 训练周期数
eval_metric: top1  # 评估指标
experiment: ''  # 实验名称
fast_norm: false  # 是否使用快速归一化
fuser: ''  # 融合器配置
gaussian_blur_prob: 0.1  # 高斯模糊的概率
gp: null  # 梯度惩罚
grad_accum_steps: 1  # 梯度累积步数
grad_checkpointing: false  # 梯度检查点
grayscale_prob: null  # 灰度化概率
head_init_bias: null  # 头部初始化偏差
head_init_scale: null  # 头部初始化比例
hflip: 0  # 水平翻转概率
img_size: null  # 图像大小
in_chans: null  # 输入通道数
initial_checkpoint: ''  # 初始检查点
input_img_mode: L  # 输入图像模式
input_key: null  # 输入键
input_size: [1,384,384]  # 输入尺寸
interpolation: ''  # 插值方式
jsd_loss: false  # 是否使用Jensen-Shannon Divergence损失
layer_decay: null  # 层衰减率
local_rank: 0  # 本地排名
log_interval: 50  # 日志间隔
log_wandb: false  # 是否使用Weights & Biases进行日志记录
lr: null  # 学习率
lr_base: 0.1  # 基础学习率
lr_base_scale: ''  # 基础学习率缩放
lr_base_size: 256  # 基础学习率大小
lr_cycle_decay: 0.5  # 循环学习率衰减
lr_cycle_limit: 1  # 学习率周期限制
lr_cycle_mul: 1.0  # 学习率周期倍数
lr_k_decay: 1.0  # K衰减学习率
lr_noise: null  # 学习率噪声
lr_noise_pct: 0.67  # 学习率噪声百分比
lr_noise_std: 1.0  # 学习率噪声标准差
mean: null  # 归一化均值
min_lr: 0  # 最小学习率
mixup: 0.0  # Mixup数据增强强度
device: cuda:0  # 设备
mixup_mode: batch  # Mixup模式
mixup_off_epoch: 0  # 关闭Mixup的周期
mixup_prob: 1.0  # Mixup概率
mixup_switch_prob: 0.5  # Mixup切换概率
model: maxvit_base_tf_384.in21k_ft_in1k # 模型名称
model_ema: false  # 是否使用指数移动平均模型
model_ema_decay: 0.9998  # 模型EMA衰减率
model_ema_force_cpu: false  # 是否强制模型EMA在CPU上
model_kwargs: {}  # 模型关键字参数
momentum: 0.9  # 动量
no_aug: false  # 是否禁用数据增强
no_ddp_bb: false  # 是否禁用分布式数据并行背板
no_prefetcher: false  # 是否禁用预取器
no_resume_opt: false  # 是否禁止恢复优化器
num_classes: null  # 类别数
opt: sgd  # 优化器类型
opt_betas: null  # 优化器betas
opt_eps: null  # 优化器epsilon
opt_kwargs: {}  # 优化器关键字参数
output: ''  # 输出目录
patience_epochs: 10  # 耐心周期
pin_mem: false  # 是否固定内存
pretrained: true  # 是否使用预训练模型
pretrained_path: null  # 预训练模型路径
ratio:  # 纵横比
- 0.75
- 1.3333333333333333
recount: 1  # 重计数
recovery_interval: 0  # 恢复间隔
remode: pixel  # 重采样模式
reprob: 0.0  # 重采样概率
resplit: false  # 是否重新分割
resume: ''  # 恢复路径
save_images: false  # 是否保存图像
scale:  # 缩放范围
- 0.08
- 1.0
sched: cosine  # 调度器类型
sched_on_updates: false  # 是否在更新时调整调度器
seed: 42  # 随机种子
smoothing: 0.1  # 标签平滑
split_bn: false  # 是否分割批归一化
start_epoch: null  # 开始周期
std: null  # 归一化标准差
sync_bn: false  # 是否同步批归一化
synchronize_step: false  # 是否同步步骤
target_key: null  # 目标键
torchcompile: null  # TorchCompile配置
torchscript: false  # 是否使用TorchScript
train_interpolation: random  # 训练插值方式
train_num_samples: null  # 训练样本数
train_split: train  # 训练分割
tta: 0  # 测试时增强
use_multi_epochs_loader: false  # 是否使用多周期加载器
val_num_samples: null  # 验证样本数
val_split: validation  # 验证分割
validation_batch_size: null  # 验证批量大小
vflip: 0.0  # 垂直翻转概率
warmup_epochs: 5  # 预热周期
warmup_lr: 1.0e-05  # 预热学习率
warmup_prefix: false  # 是否使用预热前缀
weight_decay: 2.0e-05  # 权重衰减
worker_seeding: all  # 工作人员播种
sworkers: 4  # 工作人员数
