#--encoding:utf-8--

type: detection

framework: yolov5
weights: yolov5s.pt
names: Steel_RZ.yaml    # dataset labels


img-size: 1024       # inference size (pixels)
conf-thres: 0.25    # confidence threshold
iou-thres: 0.45     # NMS IoU threshold
max-det: 1000       # maximum detections per image
device: cuda:0           # cuda device, i.e. 0 or 0,1,2,3 or cpu
view-img: false     # show results
save-txt: true      # save results to *.txt
save-conf: true     # save confidences in --save-txt labels
save-crop: true     # save cropped prediction boxes
nosave: false       # do not save images/videos
batch-size: 32      # inference batch size

debug: true        # debug mode
show: false         # show results
show-type: cv2
loader: E:\clfData\鼎信\分割\image # image folder  input
adjust: split # H split
save: true # save image
save-dir: E:\clfData\鼎信\分割\output # output folder
save-label: true # save label
save-null: true # save null label